import { TutorProfile } from '../types';

export const mockTutors: TutorProfile[] = [
  {
    id: 't1',
    userId: 'u1',
    name: 'Alice Dubois',
    contactEmail: 'alice@example.com',
    subjects: ['Math', 'Science'],
    hourlyRate: 35,
    format: 'Online',
    bio: 'Tuteur passionné de mathématiques et de sciences avec 5 ans d\'expérience pour aider les étudiants à exceller en algèbre et en physique.',
    availability: 'Lun-Mer 16h-20h',
    educationLevel: 'Master',
    institution: 'Université de Paris',
  },
  {
    id: 't2',
    userId: 'u2',
    name: 'Thomas Martin',
    contactEmail: 'thomas@example.com',
    subjects: ['English'],
    hourlyRate: 25,
    format: 'In-person',
    bio: 'Professeur d\'anglais dévoué, spécialisé dans la rédaction, la grammaire et l\'analyse littéraire.',
    availability: 'Sam-Dim 10h-14h',
    educationLevel: 'Licence',
    institution: 'Sorbonne Université',
  },
  {
    id: 't3',
    userId: 'u3',
    name: 'Catherine Leroy',
    contactEmail: 'catherine@example.com',
    subjects: ['Chemistry', 'Physics'],
    hourlyRate: 40,
    format: 'Both',
    bio: 'Ancienne professeure de biologie au lycée. Je rends les concepts scientifiques complexes faciles à comprendre.',
    availability: 'Mar, Jeu, Ven 17h-21h',
    educationLevel: 'Doctorat',
    institution: 'ENS',
  },
  {
    id: 't4',
    userId: 'u4',
    name: 'David Kim',
    contactEmail: 'david@example.com',
    subjects: ['Math', 'English'],
    hourlyRate: 30,
    format: 'Online',
    bio: 'Tuteur patient et encourageant, spécialisé dans la préparation aux examens de mathématiques et de compréhension écrite.',
    availability: 'Lun-Ven 18h-22h',
    educationLevel: 'Licence',
    institution: 'Université de Lyon',
  },
  {
    id: 't5',
    userId: 'u5',
    name: 'Eva Martinez',
    contactEmail: 'eva@example.com',
    subjects: ['Math', 'Economics'],
    hourlyRate: 50,
    format: 'In-person',
    bio: 'Tuteur de mathématiques et d\'économie de niveau universitaire. Étudiants sérieux uniquement.',
    availability: 'Week-ends 9h-17h',
    educationLevel: 'Master',
    institution: 'Polytechnique',
  },
  {
    id: 't6',
    userId: 'u6',
    name: 'Lucas Bernard',
    contactEmail: 'lucas@example.com',
    subjects: ['French', 'History', 'Geography'],
    hourlyRate: 28,
    format: 'Both',
    bio: 'Étudiant en sciences humaines, à l\'aise en français, histoire et géographie.',
    availability: 'Mer-Ven 14h-18h',
    educationLevel: 'Licence',
    institution: 'UCLouvain',
  },
];
