import { TutorProfile } from '../types';

export const mockTutors: TutorProfile[] = [
  {
    id: 't4',
    userId: 'u4',
    name: 'David Kim',
    contactEmail: 'david@example.com',
    subjects: ['Math', 'English'],
    hourlyRate: 30,
    format: 'Online',
    bio: 'Tuteur patient et encourageant, spécialisé dans la préparation aux examens de mathématiques et de compréhension écrite.',
    availability: 'Lun-Ven 18h-22h',
    educationLevel: 'Licence',
    institution: 'Université de Lyon',
  },
  {
    id: 't5',
    userId: 'u5',
    name: 'Eva Martinez',
    contactEmail: 'eva@example.com',
    subjects: ['Math', 'Economics'],
    hourlyRate: 50,
    format: 'In-person',
    bio: 'Tuteur de mathématiques et d\'économie de niveau universitaire. Étudiants sérieux uniquement.',
    availability: 'Week-ends 9h-17h',
    educationLevel: 'Master',
    institution: 'Polytechnique',
  },
  {
    id: 't6',
    userId: 'u6',
    name: 'Lucas Bernard',
    contactEmail: 'lucas@example.com',
    subjects: ['French', 'History', 'Geography'],
    hourlyRate: 28,
    format: 'Both',
    bio: 'Étudiant en sciences humaines, à l\'aise en français, histoire et géographie.',
    availability: 'Mer-Ven 14h-18h',
    educationLevel: 'Licence',
    institution: 'UCLouvain',
  },
];
