import { TutorProfile } from '../types';

export const mockTutors: TutorProfile[] = [
  {
    id: 't1',
    userId: 'u1',
    name: 'Alice Dubois',
    subjects: ['Math', 'Science'],
    hourlyRate: 35,
    format: 'Online',
    bio: 'Tuteur passionné de mathématiques et de sciences avec 5 ans d\'expérience pour aider les étudiants à exceller en algèbre et en physique.',
    availability: 'Lun-Mer 16h-20h',
    educationLevel: 'Master',
    institution: 'Université de Paris',
  },
  {
    id: 't2',
    userId: 'u2',
    name: 'Thomas Martin',
    subjects: ['English'],
    hourlyRate: 25,
    format: 'In-person',
    bio: 'Professeur d\'anglais dévoué, spécialisé dans la rédaction, la grammaire et l\'analyse littéraire.',
    availability: 'Sam-Dim 10h-14h',
    educationLevel: 'Licence',
    institution: 'Sorbonne Université',
  },
  {
    id: 't3',
    userId: 'u3',
    name: 'Catherine Leroy',
    subjects: ['Science'],
    hourlyRate: 40,
    format: 'Both',
    bio: 'Ancienne professeure de biologie au lycée. Je rends les concepts scientifiques complexes faciles à comprendre.',
    availability: 'Mar, Jeu, Ven 17h-21h',
    educationLevel: 'Doctorat',
    institution: 'ENS',
  },
  {
    id: 't4',
    userId: 'u4',
    name: 'David Kim',
    subjects: ['Math', 'English'],
    hourlyRate: 30,
    format: 'Online',
    bio: 'Tuteur patient et encourageant, spécialisé dans la préparation aux examens de mathématiques et de compréhension écrite.',
    availability: 'Lun-Ven 18h-22h',
    educationLevel: 'Licence',
    institution: 'Université de Lyon',
  },
  {
    id: 't5',
    userId: 'u5',
    name: 'Eva Martinez',
    subjects: ['Math'],
    hourlyRate: 50,
    format: 'In-person',
    bio: 'Tuteur de mathématiques de niveau universitaire. Étudiants sérieux uniquement.',
    availability: 'Week-ends 9h-17h',
    educationLevel: 'Master',
    institution: 'Polytechnique',
  },
];
